swagger: '2.0'

info:
  version: "2.0"
  title: Open311 GeoReport API
  description: Open311 allows you to get/post civic information of cities via a unified interface. The GeoReport part allows you to submit and view issues at the public local space
  termsOfService: <?>
  contact:
    name: Open311 community
    url: http://wiki.open311.org/GeoReport_v2/
    email:  discuss@lists.open311.org
  license:
    name: <?>
    url: http://

consumes:
        - application/json
        - application/xml
produces:
        - application/json
        - application/xml
        
#securityDefinitions: <?>
#security:

definitions:
  Service:
    description: A single Open311 service (type)
    properties:
      service_code:
        type: string
        description: unique identifier for the service request type
      service_name:
        type: string
        description: human readable name of the service request type
      description:
        type: string
      metadata:
        type: boolean
        description: Are there additional form fields for this service type? If true use GET service definition for that one 
      type:
        type: string
        description: Possible values realtime, batch, blackbox #todo as enum?
      keywords:
        type: string
        description: list of keywords or tags seperated by comma
      group:
        type: string
        description: Category or group to cluster different request types e.g. “sanitation”


paths:
#todo jurisdiction_id as general concept?
#todo response_format as general concept?
#todo extract an error model for responses?

  /services.{response_format}:
    get:
      summary: service types
      description: List acceptable service request types and their associated service codes. These request types can be unique to the city/jurisdiction.
      parameters:
        - name: jurisdiction_id
          in: query #fix it
          required: true
          type: string
        - name: response_format
          in: path
          required: true
          type: string
      responses:
        200:
          description: ok
          schema:
              type: array
              items:
                $ref: '#/definitions/Service'
        400:
          description: The URL request is invalid or service is not running or reachable. Client should notify us after checking URL
        404:
          description: jurisdiction_id provided was not found (specify in error response).
